name: Scheduled Playwright Tests

on:
  schedule:
    - cron: '0 0 * * *'   # run every hour
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start mock server
        run: npx json-server db.json --port 3000  --host 0.0.0.0 &

      - name: Wait for mock server to be ready
        run: npx wait-on http://127.0.0.1:3000/products
      
      - name: Run Playwright tests
        run: npx playwright test  